# Dataset and Splits
data_root: DATA
dataset_class: pydgn.data.dataset.TUDatasetInterface
dataset_name:  IMDB-BINARY
data_splits_file:  DATA_SPLITS/COLLABORATIVE_DEGREE/IMDB-BINARY/IMDB-BINARY_outer10_inner1.splits


# Hardware
device:  cpu
max_cpus:  4
max_gpus: 0
gpus_per_task:  1


# Data Loading
dataset_getter: incremental_provider.IncrementalDataProvider
data_loader:
  class_name: torch_geometric.loader.DataLoader
  args:
    num_workers : 0
    pin_memory: False


# Reproducibility
seed: 42


# Experiment
result_folder: RESULTS
exp_name: icgmm_alpha_gamma_batch_embedding
experiment: icgmm_embedding_task.EmbeddingiCGMMTask
higher_results_are_better: True
evaluate_every: 1
final_training_runs: 1

grid:
  layer_config:
    model: icgmm_batch.iCGMMBatch
    embeddings_folder: iCGMM_FULL_AUTO_RESULTS/iCGMM_BATCH_EMBEDDINGS
    batch_size:
      - 1
    shuffle:
      - False  # MUST STAY FALSE TO PRESERVE ORDERING OF NODES! OW COUNTS WON'T WORK
    previous_layers_to_use:
      - "1"  # must stay this way, SP will be implemented later as an extension for simplicity
    concatenate_on_axis: -1 # ?xAxCcurr
    emission_distribution:
      class: bayesian_nonparametric.BNPGaussianBatch
      # dataset-dependent
      prior_params:
        mu0: 3
        # lam0 controls variance of the mean. However, it depends on t=b0/a0
        # variance of mean is b0/(lam0*a0)
        lam0:
          - 0.000001
        # a0 & b0 control variance of the data. the expected variance is t=b0/a0
        a0:
          - 1
        b0:
          - 1
          - 0.09  # all variance comprised between [mean+3*0.3, mean+3*0.3]
    gamma_prior_params:
      a:
        - 1
      b:
        - 0.01
    alpha_prior_params:
      a:
        - 1
      b:
        - 0.01
    max_C: 100
    max_layers:
      - 20
    unibigram:
      - True
    aggregation:
      - mean
      - sum
    sample_neighboring_macrostate: # how to assign observation to a group 1,...,C_{l-1}
      - False  # deterministic group choice based on most probable state
    epochs:
      - 100
    engine:
      - class_name: icgmm_engine.IncrementalGibbsSamplingEngine
        args:
          engine_callback: icgmm_engine_callback.iCGMMEngineCallback
    loss:
      - icgmm_loss.iCGMMLoss
    optimizer:
      - icgmm_optimizer.iCGMMOptimizer
    scorer:
      - class_name: pydgn.training.callback.metric.MultiScore
        args:
          # used at model selection time. Should be the one on which to perform early stopping
          main_scorer: icgmm_score.iCGMMCompleteLikelihoodScore
          likelihood2: icgmm_score.iCGMMCompleteLikelihoodScore2
          C_scorer: icgmm_score.iCGMMCurrentStates
          alpha_scorer: icgmm_score.iCGMMCurrentAlpha
          gamma_scorer: icgmm_score.iCGMMCurrentGamma
    plotter: null #pydgn.training.callback.plotter.Plotter
